apiVersion: v1
kind: Secret
metadata:
  name: {{include "go-solve.fullname" .}}
type: Opaque
data:
  username: {{.Values.database.username}}
  password: {{.Values.database.password}}
  host: {{.Values.database.host}}
